git -C igris pull || git clone https://github.com/mirmik/igris
git -C nos pull || git clone https://github.com/mirmik/nos
git -C crow pull || git clone https://github.com/mirmik/crow
git -C ralgo pull || git clone https://github.com/mirmik/ralgo
git -C rabbit pull || git clone https://github.com/mirmik/rabbit
git -C RxCpp pull || git clone https://github.com/ReactiveX/RxCpp
git -C cpp-httplib pull || git clone https://github.com/yhirose/cpp-httplib
git -C rfdaemon pull || git clone https://github.com/mirmik/rfdaemon
git -C video-stream pull || git clone https://github.com/mirmik/video-stream